CREATE TABLE diagn_results (
	id		INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	servertime	TIMESTAMP(8) DEFAULT NOW(),
	appversion	VARCHAR(16),
	sysinfo		VARCHAR(128),
	remotetime	INT,
	school		VARCHAR(32),
	class		VARCHAR(32),
	name		VARCHAR(64),
	background	TEXT,
	editlog		LONGTEXT,
	editduration	SMALLINT,
	searchlog	TEXT,
	searchoper	SMALLINT,
	searchduration	SMALLINT,
	addlog		TEXT,
	addoper		SMALLINT,
	addduration	SMALLINT,
	edit2log	TEXT,
	edit2duration	SMALLINT,
	search2log	TEXT,
	search2oper	SMALLINT,
	search2duration	SMALLINT,
	add2log		TEXT,
	add2oper	SMALLINT,
	add2duration	SMALLINT,
	comments	TEXT	
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
